apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kubeskippy-infrastructure

resources:
- metrics-server.yaml
- kube-state-metrics.yaml

commonLabels:
  component: infrastructure
  managed-by: kubeskippy-demo