apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeskippy-config
  namespace: kubeskippy-system
data:
  config.yaml: |
    metrics:
      prometheusURL: "http://prometheus.monitoring:9090"
      metricsServerEnabled: true
      collectionInterval: "30s"
    ai:
      provider: "ollama"
      model: "llama2:7b"
      endpoint: "http://ollama:11434"
      timeout: "120s"
      maxTokens: 2048
      temperature: 0.7
      minConfidence: 0.6
      validateResponses: true
    safety:
      dryRunMode: false
      requireApproval: false
      maxActionsPerHour: 50
    logging:
      level: "info"
      development: false
