apiVersion: v1
kind: Service
metadata:
  name: kubeskippy-controller-manager-metrics
  namespace: kubeskippy-system
  labels:
    app.kubernetes.io/name: kubeskippy
    app.kubernetes.io/component: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP