apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kubeskippy-demo

resources:
- infrastructure/
- monitoring/
- ollama/
- kubeskippy/
- demo-apps/

commonLabels:
  project: kubeskippy-demo
  managed-by: kustomize

namespace: kubeskippy-system