apiVersion: v1
kind: Namespace
metadata:
  name: demo-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-app
  namespace: demo-apps
  labels:
    app: crashloop-app
    demo: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crashloop-app
  template:
    metadata:
      labels:
        app: crashloop-app
        issue: "crashloop"
    spec:
      containers:
      - name: app
        image: busybox
        command: 
        - sh
        - -c
        - |
          echo "Starting crashloop app..."
          # Simulate a crash after 30 seconds
          sleep 30
          echo "CRASH! Exiting with error..."
          exit 1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: crashloop-app
  namespace: demo-apps
spec:
  selector:
    app: crashloop-app
  ports:
  - port: 80
    targetPort: 8080