apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kubeskippy-monitoring

resources:
- prometheus.yaml
- grafana.yaml

commonLabels:
  component: monitoring
  managed-by: kubeskippy-demo