apiVersion: kubeskippy.io/v1alpha1
kind: HealingPolicy
metadata:
  name: cpu-spike-healing
  namespace: demo-apps
spec:
  selector:
    labelSelector:
      matchLabels:
        issue: "cpu-spike"
    resources:
      - apiVersion: apps/v1
        kind: Deployment
  
  triggers:
  - name: high-cpu-usage
    type: metric
    metricTrigger:
      query: "cpu_usage_percent"
      threshold: 80
      operator: ">"
      duration: "2m"
    cooldownPeriod: "5m"
  
  - name: cpu-anomaly-pattern
    type: metric
    metricTrigger:
      query: "cpu_usage_percent"
      threshold: 90
      operator: ">"
      duration: "1m"
    cooldownPeriod: "10m"
  
  actions:
  - name: scale-deployment
    type: scale
    description: "Scale deployment horizontally when CPU usage is high"
    scaleAction:
      direction: "up"
      replicas: 1
      minReplicas: 2
      maxReplicas: 5
    priority: 10
    requiresApproval: false
  
  - name: apply-cpu-limit-patch
    type: patch
    description: "Apply CPU limit patch to reduce throttling"
    patchAction:
      type: "strategic"
      patch: |
        spec:
          template:
            spec:
              containers:
              - name: app
                resources:
                  limits:
                    cpu: "1500m"
    priority: 20
    requiresApproval: false
  
  safetyRules:
    maxActionsPerHour: 4
    requireHealthCheck: true
    healthCheckTimeout: "2m"
  
  mode: "automatic"
