apiVersion: kubeskippy.io/v1alpha1
kind: HealingPolicy
metadata:
  name: crashloop-pod-healing
  namespace: demo-apps
spec:
  selector:
    labelSelector:
      matchLabels:
        issue: "crashloop"
    resources:
      - apiVersion: v1
        kind: Pod
  
  triggers:
  - name: high-restart-count
    type: metric
    metricTrigger:
      query: "restart_count"
      threshold: 3
      operator: ">"
      duration: "5m"
    cooldownPeriod: "5m"
  
  - name: crashloop-condition
    type: condition
    conditionTrigger:
      type: "CrashLoopBackOff"
      status: "True"
      duration: "2m"
    cooldownPeriod: "5m"
  
  actions:
  - name: restart-crashed-pods
    type: restart
    description: "Restart pods in CrashLoopBackOff"
    restartAction:
      strategy: "rolling"
      maxConcurrent: 1
    priority: 10
    requiresApproval: false
  
  - name: debug-patch
    type: patch
    description: "Apply debug environment variables"
    patchAction:
      type: "strategic"
      patch: |
        spec:
          containers:
          - name: app
            env:
            - name: DEBUG
              value: "true"
    priority: 20
    requiresApproval: false
  
  safetyRules:
    maxActionsPerHour: 5
    protectedResources:
      - apiVersion: v1
        kind: Pod
    requireHealthCheck: true
    healthCheckTimeout: "2m"
  
  mode: "automatic"
