apiVersion: kubeskippy.io/v1alpha1
kind: HealingPolicy
metadata:
  name: memory-leak-healing
  namespace: demo-apps
spec:
  selector:
    labelSelector:
      matchLabels:
        issue: "memory-leak"
    resources:
      - apiVersion: v1
        kind: Pod
  
  triggers:
  - name: high-memory-usage
    type: metric
    metricTrigger:
      query: "memory_usage_percent"
      threshold: 85
      operator: ">"
      duration: "3m"
    cooldownPeriod: "5m"
  
  - name: memory-growth-trend
    type: metric
    metricTrigger:
      query: "memory_usage_bytes"
      threshold: 90
      operator: ">"
      duration: "1m"
    cooldownPeriod: "10m"
  
  actions:
  - name: restart-leaking-pods
    type: restart
    description: "Restart pods with high memory usage"
    restartAction:
      strategy: "rolling"
      maxConcurrent: 1
    priority: 10
    requiresApproval: false
  
  - name: scale-up-deployment
    type: scale
    description: "Scale up deployment to handle memory pressure"
    scaleAction:
      direction: "up"
      replicas: 1
      minReplicas: 1
      maxReplicas: 3
    priority: 20
    requiresApproval: false
  
  safetyRules:
    maxActionsPerHour: 1  # Reduced to let AI handle more scenarios
    requireHealthCheck: true
    healthCheckTimeout: "2m"
  
  mode: "automatic"
