apiVersion: kubeskippy.io/v1alpha1
kind: HealingPolicy
metadata:
  name: service-degradation-healing
  namespace: demo-apps
spec:
  selector:
    labelSelector:
      matchLabels:
        app: flaky-web-app
    resources:
      - apiVersion: v1
        kind: Pod
  
  triggers:
  - name: high-error-rate
    type: metric
    metricTrigger:
      query: "error_rate_percent"
      threshold: 5
      operator: ">"
      duration: "2m"
    cooldownPeriod: "5m"
  
  - name: availability-issue
    type: metric
    metricTrigger:
      query: "availability_percent"
      threshold: 99.5
      operator: "<"
      duration: "5m"
    cooldownPeriod: "10m"
  
  actions:
  - name: restart-pods
    type: restart
    description: "Restart pods with high error rates"
    restartAction:
      strategy: "rolling"
      maxConcurrent: 1
    priority: 10
    requiresApproval: false
  
  - name: scale-up-service
    type: scale
    description: "Scale up to handle increased error rates"
    scaleAction:
      direction: "up"
      replicas: 2
      minReplicas: 2
      maxReplicas: 5
    priority: 20
    requiresApproval: false
  
  safetyRules:
    maxActionsPerHour: 6
    protectedResources:
      - apiVersion: v1
        kind: Pod
    requireHealthCheck: true
    healthCheckTimeout: "2m"
  
  mode: "automatic"
